### ISSUE TITLE
Ruby capstone catalog of things group project description

### ISSUE THREAD

**Issue by kalbek** [kalbek/catalog-of-things#8]
## - There are 3 members in [this project](https://github.com/kalbek/catalog-of-things/projects/1)
 - Team member 1 - @kalbek 
 - Team member 2 - @Bennyjoez 
 - Team member 3 - @massazoum 

💯

**Comment by amejid** [comment]
Hi team, 

Your project is complete!
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Information about team members present :heavy_check_mark: 
- Fair task distribution :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
